COLUMNS:
 fixed acidity: float64
 volatile acidity: float64
 citric acid: float64
 residual sugar: float64
 chlorides: foat64
 free sulfur dioxide: foat64
 total sulfur dioxide: floate64
 density: float64
 pH: float64
 sulphates: float64
 alcohol: float64
 quality: float64

TARGET_COLUMN:
 name: quality